# Generated by Django 4.2.6 on 2025-10-26 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
